### ISSUE TITLE
.increment() not working called before a .push()

### ISSUE THREAD

**Issue by mwq27** [microstates/react#11] opened 2018-10-15 17:22 UTC
I noticed this today while building a sample app with microstates.  I have a TodoState type that looks like:
```js
class TodoState {
  todos = [Todo];
  count = Number;
```

I think have a method that adds a todo to the list.  In my methdo I am trying to 
* add the todo to the list of todos
* increment the count

```js
const inc = model => {
    model.count.increment();
    model.posts.push({ id: Date.now() });
  };
```
In the above code, the increment never happens, but the push WILL happen.

Here's a code sandbox of what I'm trying to do.  If you flip lines 17 and 18, the increment will work.
https://codesandbox.io/s/13yv7ojlkl

**Comment by cowboyd** [comment] 2018-10-17 15:59
Marques,

That is _very_ interesting. I would have expected your initial example to work as well. 

That said, if it is possible it is best to include the transitions on the actual microstate models themselves like I have done in this example https://codesandbox.io/s/31x8llnjjm

This has a number of benefits:

1. There is no intermediate state emitted for the increment and the push
2. It is batched logically and can be re-used around your application
3. this is subtle but important, the `m.inc` function is stable and will not trigger re-renders when the model changes.

**Comment by mwq27** [comment] 2018-10-17 16:46
Oooh interesting, I didn't even think to put anything else really on the models.  I'll update my code to do it that way instead.  

Also great work on this library!  I was at Framework Summit a few weeks ago when you talked about this and it got me really interested.

**Comment by taras** [comment] 2019-02-08 20:21
@cowboyd did we fix this?

**Comment by cowboyd** [comment] 2019-02-08 20:35
I don't know actually. The problem is that the model reference is "stale". Note that the changes in https://github.com/microstates/microstates.js/pull/317 will make it no longer chainable.

**Comment by taras** [comment] 2019-02-11 20:01
I'm going to close this issue. @mwq27 feel free to reopen it if this issue is not resolved for you.

**Closed by taras** 2019-02-11 20:01 UTC
Labels: triage
